name: ligdicash
description: Librairie Dart pour manipuler l'API de Ligdicash
version: 1.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  http: ^1.2.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

homepage: https://github.com/Ligdicash/ligdicash-dart
documentation: https://developers.ligdicash.com
